### ISSUE TITLE
Edublocks package?

### ISSUE THREAD

**Issue by birving2** [PiNet/PiNet#137]
I'd love to install Edublocks on my PiNet server but so far have not been able to. Has anyone had any success?

**Comment by gbaman** [comment]
The plan for Edublocks support with PiNet has always been to include it once the long awaited Raspbian package is released (assuming is released for Jessie/Stretch). 
Last I checked the main install script might cause some installations on non standard Raspbian installations, like PiNet.
@JoshuaLowe1002 any progress on a Debian/Raspbian package?

**Comment by gbaman** [comment]
Poke @JoshuaLowe1002, any updates?

**Comment by JoshuaLowe1002** [comment]
Hi yes, this should work now!

**Comment by JoshuaLowe1002** [comment]
Sorry i'm really late on this, but there is no reason it should not work now @birving2

**Comment by gbaman** [comment]
@JoshuaLowe1002 Great to hear, although I am not seeing an edublocks package in the public Raspbian/RPF apt repos or on your website? Am I looking in the wrong place?

**Comment by JoshuaLowe1002** [comment]
We haven't got to the debian package stage purely because of this > https://github.com/AllAboutCode/EduBlocks/issues/26#issuecomment-434043481 Once this update is done I plan on packaging the link package up which should be a really easy thing to do now. However, i don't see a reason why the installer which has been updated since this issue was opened should not work with PiNet.

**Comment by JoshuaLowe1002** [comment]
Is there a way in PiNet to run a curl command to install stuff across all the Pi's, have it install something and then stay there?

**Comment by gbaman** [comment]
@JoshuaLowe1002 It is possible - http://pinet.org.uk/articles/advanced/editing-outside.html
But, the key thing about this is it is not maintainable long term, hence why I don't integrate any software anymore that isn't installed via a package manager (e.g. Apt or Pip).

Otherwise, it becomes very difficult to handles updates for example long term.

**Comment by JoshuaLowe1002** [comment]
Understood. 

Once the new EduBlocks revision is out, it should be much easier to package up.

**Comment by JoshuaLowe1002** [comment]
Probably will actually be a Pip install
