### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by trimdeck** [PiNet/PiNet#33]
Hi,

I have tried to install pinet and hit some problems.

Every time I start up pinet it says there is an update (0.10.46), which I install and then update pinet as recommended.

But this happens every time I start up pinet. The same update.

After two times of going through update I just cancelled and went ahead and copied the boot files to an SD and tried starting up the Pi, but it is unable to connect to pinet and spits out same kernal panic message as if pinet server was not even connected to the switch.

I tried doing the installation again through the option in the 'Other' menu. But had the same problem...

Any ideas?

Many thanks

**Comment by trimdeck** [comment]
![img_20150819_194355](https://cloud.githubusercontent.com/assets/11727267/9368728/ef0cba5a-46bc-11e5-878c-96a2773a33e8.jpg)
 I also get this at the start but that might just be because I am running pinet from the commend line - no gui?

**Comment by gbaman** [comment]
It sounds very like you are for some odd reason running an ancient version?
The 0.10.x releases were back when the project was Raspi-LTSP.
It was only when the release numbers hit 1.x.x that the name was officially changed and the old Raspi-LTSP repository frozen.
0.10.46 is the most recent (and likely final update) Raspi-LTSP release.
This causes me to believe you may have by mistake installed Raspi-LTSP (which is not longer supported) instead of PiNet.

Your best path forward is do a full reinstall of Ubuntu (this is very important) and follow the official installation documentation on the PiNet site.
http://pinet.org.uk/articles/installation/getting_started.html

Let me know if that sorts the issue.

**Comment by trimdeck** [comment]
right at the beginning we typed wget --content-disposition http://bit.ly/pinetbeta

but then had to download a python file - would that have anything to do with it?

**Comment by trimdeck** [comment]
so I just cracked it! I did a full rebuild of the LTSP raspberry pi image and it just booted up!

From the main menu - PiNet shows it is 1.013 so that looks ok (which I think it was before as well??) not sure what was going on with the update message :/

Thanks - will enjoy using this :D
